spring:
  datasource:
    url: jdbc:mysql://localhost:3306/{schema name}
    username: root
    password: {your password}
  flyway:
    enabled: true
    baseline-on-migrate: true
  jwt:
    secret: {base64key}
    expiration: {expiration in milliseconds}