CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,  -- use SERIAL in Postgres instead of AUTO_INCREMENT
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER'
);

ALTER TABLE expense
ADD COLUMN user_id BIGINT,
ADD CONSTRAINT fk_user_expense FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;